### ISSUE TITLE
Whatsapp: preview_url

### ISSUE THREAD

**Issue by avdb** [messagebird/php-rest-api#120]
Do you allow sending the parameter preview_url for whatsApp messages?
https://developers.facebook.com/docs/whatsapp/api/messages/text#urls

**Comment by noamb3** [comment]
I need this feature as well

**Comment by CoolGoose** [comment]
Hi @avdb / @noamb3  we currently don’t support setting the preview_url in the API requests. However preview_url is by default, enabled for all WA messages sent through the Conversations API
