### ISSUE TITLE
`Client::CLIENT_VERSION` says `2.0.0-prerelease` on `v2.0.0` tag

### ISSUE THREAD

**Issue by ruudk** [messagebird/php-rest-api#175]
https://github.com/messagebird/php-rest-api/blob/398eb8910095a0f11ed319aefa2fa128d4a4e197/src/MessageBird/Client.php#L22

**Comment by CoolGoose** [comment]
Thank you @ruudk . We've pushed 2.0.1 with 2.0.1 CLIENT_VERSIOn
