### ISSUE TITLE
curl timing out one third of the time when sending sms

### ISSUE THREAD

**Issue by patillades-eurocios** [messagebird/php-rest-api#19]
When using the messages->create API method, one third of my attempts are ending up throwing exceptions with the message "Resolving timed out after 2514 milliseconds". So I was wondering if the number of seconds on `curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 2);`  on performHttpRequest@HttpClient could become a config parameter, or maybe I should fork the repo?

**Comment by samwierema** [comment]
Hi @patillades-eurocios,

Thanks for opening this issue. We're looking at your suggestion of including it as a configuration parameter and will get back to you once we've settled on a solution. In the meantime, we suggest either manually changing the value, or cloning the repository and implementing a fix yourself.

Should you choose the latter please know that pull requests are always welcome!
