### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ruudk** [messagebird/php-rest-api#191]
Currently latest tagged release produces deprecations on PHP 8.1.

These are fixed in [`main`](https://github.com/messagebird/php-rest-api/compare/v2.1.0...master). 

Could you please tag a new release so that we can upgrade?

**Comment by CoolGoose** [comment]
@ruudk yes it's on the plan for this week to release it.

**Comment by CoolGoose** [comment]
@ruudk and it's tagged.
