### ISSUE TITLE
Button use in HSM

### ISSUE THREAD

**Issue by digitaltrustkz** [messagebird/php-rest-api#202]
Hello, 

We couldn't find any example and code how can we add parameter to Dynamic Button URL?  Is it not possible with PHP SDK?

**Comment by dennisvdvliet** [comment]
Hi @digitaltrustkz have you looked at this example: https://github.com/messagebird/php-rest-api/blob/9bf98a14c7f509df5601cb8ac29e371aa7306b45/examples/conversations/create-hsm.php ?

**Comment by dennisvdvliet** [comment]
Closing as part of cleanup. Feel free to re-open if needed.
