### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by ultraesteban** [messagebird/php-rest-api#203]
Hey guys, 

All of a sudden we're receiving this error (SSL certificate problem: certificate has expired) using latest release 3.1.1 on our production server who was working perfectly.
Never had this error before, maybe there's a problem on the crt bundle? 
I've noticed the certificate for rest.messagebird.com expires this saturday 9th, maybe related?

Thanks!

**Comment by vallerion** [comment]
Hi @ultraesteban,

It looks weird due to certificates will be valid until Sunday, 10 July 2022, 02:59:59 EEST. We scheduled certificates change on tomorrow you can subscribe for updates [here](https://status.messagebird.com/incidents/lpl1syk9t0v1).

**Comment by vallerion** [comment]
Hello @ultraesteban,

we had an incident with SSL certificates which caused issue for SDK users. https://status.messagebird.com/incidents/cbf1zx7yj9wj
Also we [updated our ca-bundle](https://github.com/messagebird/php-rest-api/pull/204) at this SDK so for now everything should work fine.
