### ISSUE TITLE
no (correct) recipients found.

### ISSUE THREAD

**Issue by baaskoen** [messagebird/php-rest-api#21]
I'm trying out the API and I'm getting the following error:

> no (correct) recipients found. Note: during your test period you can only send messages to yourself.

I'm simply setting the receiver to: `array($myNumber)`

What exactly is meant with `during your test period you can only send messages to yourself.`? Is there some option/account setting where I can set a default recipient number?

**Comment by samwierema** [comment]
Hi @baaskoen, I see you've closed this already, but here's an explanation on the error: when you request free credits after you've created an account, the number with which you've requested the credits will be the only number to which you can send (using the free credits). If you try to send to any other number (even in combination with your number) it will fail and you'll get the error message you noted.

Hope that explains it. If you have more questions and/or feedback, let us know.

**Comment by baaskoen** [comment]
Thank you @samwierema for the explanation. I had figured this out already. Someone else requested the free credits so I had no idea this number existed.

**Comment by DmitryBachin** [comment]
I have completely the same situation, but I am using the same number which I have written when I applied for the test credits.

**Comment by epels** [comment]
Hi @DmitryBachin! Sounds like something is going wrong there indeed.
Could you please contact our support team via https://www.messagebird.com/en/contact? They will work with you to resolve the issue. Thanks!

**Comment by DmitryBachin** [comment]
@epels I am so sorry for this message.
It was just a typo in my own code, so the key "recipients" was not included into the request body.
I am sorry that I have disturbed you.

**Comment by epels** [comment]
@DmitryBachin No worries, that happens! Good to hear it worked out for you: have fun building something awesome! Just let us know if there's anything we can help out with.

**Comment by marqueetest** [comment]
I am trying to send the sms through message bird with following parameters
var params = {
                'originator': '+61xxxxxx',
                'recipients': ['+61xxxxxx'],
                'body': 'Hello, world!'
            };
but it is showing the following error during execution:-
no (correct) recipients found. Note: during your test period you can only send messages to your own number (+).
how can i fix this in nodejs kindly help

**Comment by mh1k3code** [comment]
i am also getting the same error but i have used the same number as that for my trial run its not working
***** Fatal error: Uncaught MessageBird\Exceptions\RequestException: no (correct) recipients found ****

**Comment by CoolGoose** [comment]
@mh1k3code can you paste your code sample please ? Thank you.
