### ISSUE TITLE
PHP 8.3

### ISSUE THREAD

**Issue by chris-skilltech** [messagebird/php-rest-api#221]
I noticed that this repo hasn't been updated in a little while. 

Are there plans to add PHP 8.3 compatibility? I appreciate it may just work but it isn't officially supported via packagist / composer.

**Comment by ruudk** [comment]
While at it, let's also support PHP 8.4 😉

**Comment by ruudk** [comment]
Handled in https://github.com/messagebird/php-rest-api/pull/222
