### ISSUE TITLE
Messagebird API Lookup function does not reset on consecutive requests

### ISSUE THREAD

**Issue by sandermijnos** [messagebird/php-rest-api#26]
I am using the messagebird API to send messages through Messagebird from a client website.

This works very well with a single lookup ($nummer is the number to check):

try {
$Lookup = $MessageBird->lookup->read($nummer);
} catch (\MessageBird\Exceptions\AuthenticateException $e) {
echo 'Onjuiste toegangscode';
} catch (\Exception $e) {
var_dump($e->getMessage());
}

The response is good, it shows a hlr object when the number is valid and no hlr object when the number is not:

MessageBird\Objects\Lookup Object
(
    [href:protected] => https://rest.messagebird.com/lookup/31645621997
    [countryCode:protected] => NL
    [countryPrefix:protected] => 31
    [phoneNumber:protected] => 31645621997
    [type:protected] => mobile
    [formats:protected] => stdClass Object
        (
            [e164] => +31645621997
            [international] => +31 6 45621997
            [national] => 06 45621997
            [rfc3966] => tel:+31-6-45621997
        )

    [hlr:protected] => stdClass Object
        (
            [id] => 0d9a26f5557bc00c02407d2h55197935
            [network] => 20412
            [details] => stdClass Object
                (
                    [country_iso] => NLD
                    [country_name] => Netherlands
                    [imsi] => 204125900111663
                    [location_iso] => nl
                    [location_msc] => 31653
                    [ported] => 0
                    [roaming] => 0
                    [status_desc] => 
                )

            [reference] => yoloswag3001
            [status] => active
            [createdDatetime] => 2016-08-23T07:52:32+00:00
            [statusDatetime] => 2016-08-23T07:52:34+00:00
        )

)

However, when i use the same lookup function in a loop (to verify multiple numbers from an Excel input form), the API returns a hlr oject with a status "valid" for each number, even if the number is bogus, example output:

MessageBird\Objects\Lookup Object
(
    [href:protected] => https://rest.messagebird.com/lookup/31645621997
    [countryCode:protected] => NL
    [countryPrefix:protected] => 31
    [phoneNumber:protected] => 31645621997
    [type:protected] => mobile
    [formats:protected] => stdClass Object
        (
            [e164] => +31645621997
            [international] => +31 6 45621997
            [national] => 06 45621997
            [rfc3966] => tel:+31-6-45621997
        )

    [hlr:protected] => stdClass Object
        (
            [id] => 0d9a26f5557bc00c02407d2h55197935
            [network] => 20412
            [details] => stdClass Object
                (
                    [country_iso] => NLD
                    [country_name] => Netherlands
                    [imsi] => 204125900111663
                    [location_iso] => nl
                    [location_msc] => 31653
                    [ported] => 0
                    [roaming] => 0
                    [status_desc] => 
                )

            [reference] => yoloswag3001
            [status] => active
            [createdDatetime] => 2016-08-23T07:52:32+00:00
            [statusDatetime] => 2016-08-23T07:52:34+00:00
        )

)
MessageBird\Objects\Lookup Object
(
    [href:protected] => https://rest.messagebird.com/lookup/31611111111
    [countryCode:protected] => NL
    [countryPrefix:protected] => 31
    [phoneNumber:protected] => 31611111111
    [type:protected] => mobile
    [formats:protected] => stdClass Object
        (
            [e164] => +31611111111
            [international] => +31 6 11111111
            [national] => 06 11111111
            [rfc3966] => tel:+31-6-11111111
        )

    [hlr:protected] => stdClass Object
        (
            [id] => 0d9a26f5557bc00c02407d2h55197935
            [network] => 20412
            [details] => stdClass Object
                (
                    [country_iso] => NLD
                    [country_name] => Netherlands
                    [imsi] => 204125900111663
                    [location_iso] => nl
                    [location_msc] => 31653
                    [ported] => 0
                    [roaming] => 0
                    [status_desc] => 
                )

            [reference] => yoloswag3001
            [status] => active
            [createdDatetime] => 2016-08-23T07:52:32+00:00
            [statusDatetime] => 2016-08-23T07:52:34+00:00
        )

)

The second number is bogus but does still return a hlr object with a status "active".

I have tried unsetting $Lookup after each lookup and i have tried to build in a sleep(5) to pause the loop, but neither resolve the problem.

The problem seems to occur because $MessageBird->lookup seems to save the hlr block after the first lookup, even if you call the function again.

**Comment by sotoz** [comment]
Hello,
Would you mind sharing the code of the loop that fetches the hlrs?

**Comment by sandermijnos** [comment]
The loop code is as follows (note: there is a bit of code in there from an Excel input functionality):

$data = new Spreadsheet_Excel_Reader($_SERVER['DOCUMENT_ROOT'].'/temp/'.$_FILES['xls_file']['name'], FALSE);
$rowcount = $data->rowcount(0);
for($row = 2; $row <= $rowcount; $row++) {
$sms_receiver = trim($data->val($row, 'A'));
try {
$Lookup = $MessageBird->lookup->read($nummer);
} catch (\MessageBird\Exceptions\AuthenticateException $e) {
echo 'Onjuiste toegangscode';
} catch (\Exception $e) {
var_dump($e->getMessage());
}
}

$messagebird is set at the start of the file:
$MessageBird = new \MessageBird\Client($apikey);


Note that i have created a workaround by re-creating the object each time at the start of the loop, as follows:

$data = new Spreadsheet_Excel_Reader($_SERVER['DOCUMENT_ROOT'].'/temp/'.$_FILES['xls_file']
['name'], FALSE);
$MessageBird = new \MessageBird\Client($apikey);
$rowcount = $data->rowcount(0);
for($row = 2; $row <= $rowcount; $row++) {
$sms_receiver = trim($data->val($row, 'A'));
try {
$Lookup = $MessageBird->lookup->read($nummer);
} catch (\MessageBird\Exceptions\AuthenticateException $e) {
echo 'Onjuiste toegangscode';
} catch (\Exception $e) {
var_dump($e->getMessage());
}
}

**Comment by samwierema** [comment]
@sandermijnos we've identified the following bug: the same HLR is returned for different number in subsequent requests. We'll be implementing a patch, and will let you know when it's been resolved.

**Comment by samwierema** [comment]
@sandermijnos this issue should now be fixed in version `1.5.1`.
