### ISSUE TITLE
HTTPClient injection through constructor is wrongfully reused

### ISSUE THREAD

**Issue by SpacePossum** [messagebird/php-rest-api#29]
When construction the client you can only pass one HTTPClient; @ see
https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/Client.php#L95
The client is used for both `chat` and `messaging` while the services have diff. end-points.

I would like to suggest to add an additional parameter to the constructor allowing two HTTPClient's to be passed, i.e. something like this;

``` php
public function __construct($accessKey = null, Common\HttpClient $httpClient = null, Common\HttpClient $httpChatClient = null)
```

Since the class is not declared final the change would be a BC break, so I would like to suggest doing the change on a new 2.x line and release the change on a 2.0 tag.

**Comment by sotoz** [comment]
Hello SpacePossum,
Thank you for your help and your helpful feedback. We will check this matter and reply to you as soon as possible. You are right about this being a breaking change so we would like to pay extra attention at this.

**Comment by samwierema** [comment]
@SpacePossum this would indeed be a breaking change, and would require at least a major version upgrade. At this stage we're not yet considering a major version upgrade.

An alternative could be to create two child classes that inherit from `Client`, e.g. `ChatClient`. That would not be a backwards incompatible change, and would allow specific configuration for the REST API and Chat API respectively. 

For our reference, do you currently have a specific requirement that would allow for two separate `HttpClient` instances?

**Comment by SpacePossum** [comment]
Hi,

Thanks for the feedback and thoughts. Currently I have no real need for the two separate clients. 

I came to this issue when working on https://github.com/messagebird/php-rest-api/pull/28.
There I have a use case for injecting the client such that I can prepare/configure it myself and set a different timeout than the default. So for now I'm good :)

**Comment by SpacePossum** [comment]
@samwierema please ping me when a new major release is being considered, I'm happy to see if I can help out at that time. Thanks for reply :+1:
