### ISSUE TITLE
Mac OSX 10.9.5 local development gives SSL certificate problem

### ISSUE THREAD

**Issue by dataground** [messagebird/php-rest-api#3]
On Mac OSX 10.9.5 a call to the API gives an SSL error
    
    MessageBird\Exceptions\HttpException: SSL certificate problem: unable to get local issuer certificate

I did not find out why the MessageBird Cert is not trusted. But the error does not seem to occur on other os (linux etc)

One can switch off verification in Development by using this hack in vendor/messagebird/php-rest-api/src/MessageBird/Common/HttpClient.php:106
   
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

Maybe it is possible to add a function to skip SSL verification in the high level API?

**Comment by samwierema** [comment]
This issue is commonly caused by a CA certificate nog being present on the system that is making the request. You'll find the certificate that is needed here https://www.digicert.com/CACerts/DigiCertSHA2SecureServerCA.crt.
