### ISSUE TITLE
No ID in the response

### ISSUE THREAD

**Issue by dhunink** [messagebird/php-rest-api#34]
Hi,

according to the documentation each request should get a response including an ID attribute.
However, when I'm doing a post request including a scheduled dateTime, the response does not include this ID.
What am I doing wrong here?

To replicate, here's the call I'm making in PHP:

```
$message 					= new \MessageBird\Objects\Message();
$message->scheduledDatetime = "2017-01-07T18:00:00+00:00";
$message->originator 		        = 'Mister X';
$message->recipients 		        = array('0641107800')
$message->body 				= "Test message";
```

The server response in JSON is as following:
```
body
	
	"Dit bericht wordt 2 dagen van te voren verzonden"
datacoding
	
	"plain"
direction
	
	"mt"
gateway
	
	2
mclass
	
	1
originator
	
	"Sector X"
recipients
	
	Object { totalCount=1,  totalSentCount=0,  totalDeliveredCount=0,  meer...}
reference
	
	null
scheduledDatetime
	
	"2017-01-07T18:00:00+00:00"
type
	
	"sms"
typeDetails
	
	Object {}
validity
	
	null
```

This differs from the example response (as shown on ([https://developers.messagebird.com/docs/messaging#messaging-send](https://developers.messagebird.com/docs/messaging#messaging-send )) on several variables but most importantly to me, this ID parameter is missing, which makes it impossible to store the ID and retrieve it's status on a different moment in time.

For a bit more insight: I'm developing an application that allows the user of the application to schedule messages for certain registered members. Therefore I need to determine for each user which messages are scheduled already, and therefore need their ID's to do a GET request (or even a POST delete request).

Any thoughts are more then welcome. Thanks!

**Comment by dstotijn** [comment]
Hi @dhunink,

When you create a message using our PHP library, the `Message` object that is returned has a `protected` property called `id`. When you `var_dump()` you won't see it. You can call the `getId()` function on the object to get the ID that was returned by the REST API.

Example:

```php
$client = new \MessageBird\Client('YOUR_ACCESS_KEY');

$message = new \MessageBird\Objects\Message();
$message->originator = 'MessageBird';
$message->recipients = [31612345678];
$message->body = 'This is a test message.';

try {
    $createdMessage = $client->messages->create($message);
    var_dump($createdMessage->getId());
} catch (\Exception $e) {
    echo $e->getMessage();
}
```

Let me know if you have any questions on this. Good luck!

**Comment by dhunink** [comment]
Hi @dstotijn! That absolutely did the trick; I did not realised that the ID was actually there but as a private property. Thanks for the clarification, I do have things working like a charm now 😀
