### ISSUE TITLE
Boundary conditions are not covered for timeouts in HttpClient

### ISSUE THREAD

**Issue by dnl-blkv** [messagebird/php-rest-api#38]
How to Reproduce
------------------
1. In HttpClient code, change timeout check on line 58 from:
```
if (!is_int($timeout) || $timeout < 1) {
```
to
```
if (!is_int($timeout) || $timeout <= 1) {
```
2. In HttpClient code, change connection timeout check on line 67 from:
```
if (!is_int($connectionTimeout) || $connectionTimeout < 0) {
```
to
```
if (!is_int($connectionTimeout) || $connectionTimeout <= 0) {
```

What Should Happen
---------------------
1. Some unit tests are broken because they detect the logic change which was not reflected by tests.

What Happens
--------------
1. All unit tests are passing.

**Comment by samwierema** [comment]
Hi @dnl-blkv, this has now been merged.
