### ISSUE TITLE
Since 2017-03-19 we experience regular MessageBird\Exceptions\HttpException: SSL connection timeout

### ISSUE THREAD

**Issue by value2health** [messagebird/php-rest-api#43]
MessageBird\Exceptions\HttpException: SSL connection timeout

First occurrence:

Received On
2017-03-19 19:00:30 CET
Notifier Timestamp
2017-03-19 19:00:30 CET

Could be related to updating SSL certificates? Do you regularly update the ca-bundle in the distribution?

Versions:
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
    "messagebird/php-rest-api": "1.6.2", using composer

**Comment by value2health** [comment]
Updating SSL ca-bundle seems to fix this issue:

https://github.com/messagebird/php-rest-api/pull/44

**Comment by samwierema** [comment]
Hi @value2health, sorry to hear you're having issues with the certificate. I don't think we've updated it recently, so that could definitely be the issue. We'll have a look at your PR today.

**Comment by samwierema** [comment]
Hi @value2health, this has now been merged in #44. Thanks!
