### ISSUE TITLE
Updated Certificate

### ISSUE THREAD

**Issue by coderiekelt** [messagebird/php-rest-api#47]
Hello,

I have just gotten word that the certificate that is used for the REST api is being updated, will this also impact applications utilizing this library?

If so, will this library be updated to support the new certificate?

**Comment by dstotijn** [comment]
Hi @coderiekelt,

Good question :) The CA bundle shipped with this library (https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/ca-bundle.crt) contains the CA Root certificates, which will keep working in combination with our new SSL certificate once we start using it. So no updates/changes are required.
