### ISSUE TITLE
MessageBirdException improvement

### ISSUE THREAD

**Issue by krlove** [messagebird/php-rest-api#59]
Hi MessageBird team,

I'm having some inconveniences handling `MessageBirdException`s. 
My code looks like this:

    try {
        $this->messageBirdClient->messages->create($message);
    } catch (MessageBirdException $e) {
        $this->writeln($e->getMessage()); // console output
    }

It works fine but in case of catching certain exceptions types `$e->getMessage()` returns null (see https://github.com/messagebird/php-rest-api/blob/master/src/MessageBird/Common/ResponseError.php#L44). At the same time reasonable error message is returned in a response:

    ...
    ["errors"]=>
          array(1) {
            [0]=>
            object(stdClass)#62 (3) {
              ["code"]=>
              int(2)
              ["description"]=>
              string(42) "Request not allowed (incorrect access_key)"
              ["parameter"]=>
              string(10) "access_key"
            }
          }
    ...

Because of this I have to handle these cases separately which is not what I want to do.

My suggestion is to add error description to `MessageBirdException` in all cases.

Thanks,
Andrey

**Comment by epels** [comment]
Hi @krlove, thanks for submitting an issue! I definitely agree it's neater to return proper exception messages instead of null.

I created a pull request to solve this issue, it can be found here: #67. Does this solve your issue?
