### ISSUE TITLE
when i run it gives me error :Connection timed out after 2003 milliseconds

### ISSUE THREAD

**Issue by ankita1612** [messagebird/php-rest-api#63]
Hi,

I m using rest API to send sms. On localhost sms functionality works well. when i upload it on live server it gives me error :Connection timed out after 2003 milliseconds

**Comment by epels** [comment]
Hi @ankita1612, thanks for opening an issue! Hopefully you have managed to resolve this issue.

If not, you can attempt setting a higher connection timeout in the `HttpClient`. The default is 2 seconds. Here's a brief example:
```php
// Set both the $timeout and $connectionTimeout to 10 seconds
$MessageBird = new Client('YOUR_ACCESS_KEY', new HttpClient(Client::ENDPOINT, 10, 10));
```

Please let us know whether this did the trick for you - thanks!

**Comment by epels** [comment]
Hi @ankita1612, hopefully you've managed to resolve the problem based on the information above. I'm closing this issue for now: feel free to comment or re-open in case you're still running into problems!

**Comment by krishnavala-concetto** [comment]
Class "MessageBird\HttpClient" not found
