### ISSUE TITLE
Test message with test number not sending to mobile

### ISSUE THREAD

**Issue by imchaitanyadesai** [messagebird/php-rest-api#65]
It give the response that message is sent. But did not display in sms overview and not able to get on mobile as well.

From the message unique id I try to get that message with this api:

`MessageBird->messages->read();`

then also in response it get no message found.

In GUI it is working perfectly fine. with api it not.

here is the response:

```
MessageBird\Objects\Message Object
(
    [id:protected] => 53ad3b2858804ca5ab5b2bb73d3d84a4
    [href:protected] => https://rest.messagebird.com/messages/53ad3b2858804ca5ab5b2bb73d3d84a4
    [direction] => mt
    [type] => sms
    [originator] => mobile number
    [body] => 072822
    [reference] => 
    [validity] => 
    [gateway] => 10
    [typeDetails] => stdClass Object
        (
        )

    [datacoding] => plain
    [mclass] => 1
    [scheduledDatetime] => 
    [createdDatetime:protected] => 2018-06-12T11:47:22+00:00
    [recipients] => stdClass Object
        (
            [totalCount] => 1
            [totalSentCount] => 1
            [totalDeliveredCount] => 0
            [totalDeliveryFailedCount] => 0
            [items] => Array
                (
                    [0] => MessageBird\Objects\Recipient Object
                        (
                            [recipient] => mobile number
                            [status] => sent
                            [statusDatetime] => 2018-06-12T11:47:22+00:00
                        )

                )

        )

    [reportUrl] => 
)
```

**Comment by Edofre** [comment]
Also currently having this issue, the recipient of the message is also the same as in my messagebird profile.

**Comment by foae** [comment]
@imchaitanyadesai, @Edofre can you please send an email at support@messagebird.com with as much details as you can regarding your issue?

**Comment by Edofre** [comment]
@foae Done, noticed that from a production account the message is being sent, but dev environment is not working.

**Comment by imchaitanyadesai** [comment]
@foae Solved. Actually I was using test access key. I talk with support team and they say generate live key and then used. I follow the step and it worked.

If any query ask support team. they will give you instant reply.
