### ISSUE TITLE
Proxy / HttpClient.php

### ISSUE THREAD

**Issue by joachim-jansen** [messagebird/php-rest-api#76]
Sometimes an specific Proxy adds a certain header. In the current version only a specific header is dismissed; but not mine. This code helps allthough it could be improved.

```
// Split the header and body
$parts = explode("\r\n\r\n", $response, 3);

if ( count( explode( "\r\n", $parts[0] ) ) === 1 ){
  array_shift( $parts );
}

list($responseHeader, $responseBody) = array ($parts[0], $parts[1]);
```

**Comment by CoolGoose** [comment]
Closing this right now since the handling is a bit different currently. If you have any actual response example we can match against please reopen the issue.

**Comment by joachim-jansen** [comment]
Please find sample response content:

Debug shows normal \r\n which are newlines

HTTP/1.1 200 Connection established\r\n
\r\n
HTTP/1.1 200 OK\r\n
Server: nginx\r\n
Date: Thu, 02 Sep 2021 14:12:24 GMT\r\n
Content-Type: application/json; charset=UTF-8\r\n
Content-Length: 55\r\n
Vary: Accept-Encoding\r\n
X-CLOUD-TRACE-CONTEXT: REMOVED;o=0\r\n
Access-Control-Allow-Headers: Authorization, Content-Type\r\n
Access-Control-Allow-Origin: *\r\n
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE\r\n
Access-Control-Allow-Credentials: true\r\n
Pragma: no-cache\r\n
Expires: 0\r\n
Cache-Control: must-revalidate, post-check=0, pre-check=0\r\n
Via: 1.1 google\r\n
Alt-Svc: clear\r\n
\r\n
{"payment":"prepaid","type":"credits","amount":9299.85}
