### ISSUE TITLE
1.13.0 was released on Github, but is not available on Packagist

### ISSUE THREAD

**Issue by paul-thebaud** [messagebird/php-rest-api#84]
Hello,

I see on Github that the 1.13.0 was release 12 days ago, but when I try to update my package from my app, the higher version I got is 1.10.x.
When I go to the [packagist page](https://packagist.org/packages/messagebird/php-rest-api), I see that only 1.10.x is available as non-beta release.

Is it normal?

**Comment by modprobe** [comment]
Hi @paul-thebaud!

Thank you for the heads-up, 1.13.0 is now available on Packagist as well. Enjoy!

**Comment by paul-thebaud** [comment]
Hi, thank you, it works now! Well done :)
