### ISSUE TITLE
Documentation for endpoint `GET /hlr` is missing

### ISSUE THREAD

**Issue by dwilmer-karify** [messagebird/php-rest-api#86]
On https://developers.messagebird.com/api/hlr/, there is a line `GET /hlr` under "Available HTTP Methods". I can't find any documentation for this end point anywhere else on the page. From the documentation for `GET /messages` I can gather that I can filter using a limit, offset, and an msisdn, but what other search fields are available?

**Comment by CoolGoose** [comment]
@dwilmer-karify I apologise for the late reply.  The documentation over https://developers.messagebird.com/api/hlr/ should contain all the necessary samples now.
