### ISSUE TITLE
Please use semver and release 1.14.1

### ISSUE THREAD

**Issue by webmaster777** [messagebird/php-rest-api#94]
Following semantic versioning (https://semver.org/), your "oops" version of 1.14.0.1 does not fit as proper release tag. You should issue a 1.14.1 patch release instead. 

Also, if you want to use the version of your package inside your package, there are alternatives to using a hardcoded string

See:
* https://packagist.org/packages/sebastian/version
* https://packagist.org/packages/ocramius/package-versions

Package managers could interpret  1.14.0.1 with the .1 suffix being a pre-release or build metadata info and not a real version.

**Comment by marcelcorso** [comment]
hey @webmaster777. You are right we did something bad there. We'll release 1.14.1 very soon. 

I also <3 the idea of not hardcoding the version inside the package. `ocramius/package-versions` looks like a good contender. 
Could you do a PR for that? 🙏

**Comment by marcelcorso** [comment]
https://github.com/messagebird/php-rest-api/releases/tag/1.14.1

**Comment by webmaster777** [comment]
see #97. It has some implications so I hope you can clear up what you want as consequence.
