### ISSUE TITLE
conversations/create.php JSON is not a valid format

### ISSUE THREAD

**Issue by GewoonSibrand** [messagebird/php-rest-api#95]
The example code from the conversations/create.php file gives the following message: 'MessageBird\Exceptions\RequestException: JSON is not a valid format'.

**Comment by modprobe** [comment]
Thanks for your report! You're absolutely right, it's using the wrong method. 

I will fix this shortly, in the meantime, you can replace 
```php
$messageBird->conversations->create($message)
```

with 

```php
$messageBird->conversations->start($message)
```

**Comment by GewoonSibrand** [comment]
Thank you!
